# Generated by Django 2.0.6 on 2018-07-05 01:42

from django.db import migrations, models
import django.utils.timezone
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=notes.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
