# Generated by Django 2.0.6 on 2018-07-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180711_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
