# Generated by Django 2.0.6 on 2018-07-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notestimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
