# Generated by Django 2.0.6 on 2018-07-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='notestimeline',
            name='note',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
            preserve_default=False,
        ),
    ]
