# Generated by Django 2.1 on 2018-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('notes', '0010_auto_20180719_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
